version: "3.9"
services:
  redis:
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      - ./backend/app/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    restart: "no"

  bot:
    build: backend/bot
    env_file:
      - .env
    depends_on:
      - redis

  app:
    build: backend/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - UPLOAD_IMAGES_PATH=/static_images
    volumes:
      - ./nginx/static_images:/static_images

  nginx_site:
    build: nginx/site
    ports:
      - "80:80"
    volumes:
      - ./nginx/data/nginx/locally:/etc/nginx/conf.d
      - ./nginx/static_images:/usr/share/nginx/html/static_images
    depends_on:
      - app

  nginx_admin:
    build: nginx/admin
    ports:
      - "2000:80"
    volumes:
      - ./nginx/static_images:/usr/share/nginx/html/static_images
    depends_on:
      - db
