version: "3.9"
services:
  redis:
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  bot:
    build: backend/bot
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TELEGRAM_USER_PASSWORD=1uu
      - TELEGRAM_ADMIN_PASSWORD=1a
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./backend/bot/data:/bot/data

  app:
    build: backend/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/data/nginx:/etc/nginx/conf.d
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    depends_on:
      - app
      - bot