### Проверить соединение
GET http://localhost:5000/

### Отправить POST-запрос с контактами
POST http://2a00:f940:2:4:2::2925:5000/api/contact
Content-Type: application/x-www-form-urlencoded

name=Homer&contact_method=telegram&contact=+7915999199&message=Некоторое сообщение

### test
GET http://stonemason67.ru/.well-known/acme-challenge/hello.txt