# Используйте официальный образ Nginx
FROM nginx:alpine

COPY config/default.conf /etc/nginx/conf.d/

# Скопируйте файлы из вашей папки dist в директорию Nginx
COPY dist/ /usr/share/nginx/html/

# Запуск Nginx в фоновом режиме
CMD ["nginx", "-g", "daemon off;"]
